### PR TITLE
Remove dirty stack cases

### LINKED ISSUE #506: Review stack handling (especially 32-bit vs 64-bit dirty upper bits)
If we add an `assert(i64 & 0xffffffff00000000) == 0)` to `as<uint32_t>()` we get a lot of failures. As an example:

```
[ RUN      ] end_to_end.milestone2
Assertion failed: ((i64 & 0xffffffff00000000) == 0), function as, file /Users/alex/Projects/fizzy/lib/fizzy/value.hpp, line 59.
Abort trap: 6
```

The first instruction unit test failing is `execute_numeric.i32_eqz`. Haven't investigated further. The test branch is in `value_assert`.

This came up https://github.com/wasmx/fizzy/pull/464#discussion_r475245546.

### PR DESCRIPTION
**Pull request by axic**
Fixes #506.

### CODE REVIEW

File: test/unittests/execute_numeric_test.cpp [hunk 1]
```diff
@@ -64,8 +64,8 @@ TEST(execute_numeric, i32_eqz)
     EXPECT_THAT(execute_unary_operation(Instr::i32_eqz, 0), Result(1));
     EXPECT_THAT(execute_unary_operation(Instr::i32_eqz, 1), Result(0));
     // Dirty stack
-    EXPECT_THAT(execute_unary_operation(fizzy::Instr::i32_eqz, 0xff00000000), Result(1));
-    EXPECT_THAT(execute_unary_operation(fizzy::Instr::i32_eqz, 0xff00000001), Result(0));
+    // EXPECT_THAT(execute_unary_operation(fizzy::Instr::i32_eqz, 0xff00000000), Result(1));
```
Comment (axic) [inline test/unittests/execute_numeric_test.cpp:67]: These are just invalid as they would fail validation.

File: test/unittests/value_test.cpp [hunk 2]
```diff
@@ -47,13 +47,22 @@ TEST(value, constructor_from_floating_points)
...
+    EXPECT_EQ(v.as<int64_t>(), 0xfffffffe);
+    EXPECT_EQ(v.as<int32_t>(), -2);
+}
+
+TEST(value, as_integer_64bit_value)
 {
     const Value v{0xfffffffffffffffe};
     EXPECT_EQ(v.as<uint64_t>(), 0xfffffffffffffffe);
-    EXPECT_EQ(v.as<uint32_t>(), 0xfffffffe);
+    // EXPECT_EQ(v.as<uint32_t>(), 0xfffffffe);
```
Comment (axic) [inline test/unittests/value_test.cpp:63]: Likewise these should be just removed.

**Review by chfast — APPROVED** [review]

**Review by chfast — APPROVED** [review]

**Review by gumb0 — APPROVED** [review]
