### PR TITLE
test: Improve spectest runner output

### LINKED ISSUE #450: Limit verbosity of fizzy-spectests
The output from `fizzy-spectests` is quite large as it reports status of every executed test case. I expect users are mostly interested in failures. Some ideas how to improve it.

1. Skip `PASSED` reports by default. Easy to implement.
2. Repeat status of each file in the end. This will allow at least quickly find the file with failures and repeat the run on the subset of files.
3. Use "dot notation" per file. Each test result is represented by a single character. E.g.
   ```
   binary.wast: ......F.....s.....
   Line 98: assert_return FAILED Incorrect returned value. Expected: 9219994337134247936 (0x7ff4000000000000) Actual: 0 (0x0)
   Line 99: assert_return SKIPPED Unsupported feature: Floating point instruction.
   ```

### PR DESCRIPTION
**Pull request by gumb0**
Closes #450 

Current output without skipped:
```
> bin/fizzy-spectests ~/dev/wasm-spec/test/core/json/float_memory/
Running tests from /home/andrei/dev/wasm-spec/test/core/json/float_memory/float_memory.json
..s..ssFs..s..s..s..ssFs..s..s..s..ssFs..s..s..s..ssFs..s..s..s..ssFs..s..s..s..ssFs..s..s
Line 21: assert_return FAILED Incorrect returned value. Expected: 2141192192 (0x7fa00000) Actual: 0 (0x0)
Line 46: assert_return FAILED Incorrect returned value. Expected: 9219994337134247936 (0x7ff4000000000000) Actual: 0 (0x0)
Line 73: assert_return FAILED Incorrect returned value. Expected: 2141192192 (0x7fa00000) Actual: 0 (0x0)
Line 98: assert_return FAILED Incorrect returned value. Expected: 9219994337134247936 (0x7ff4000000000000) Actual: 0 (0x0)
Line 125: assert_return FAILED Incorrect returned value. Expected: 2144337921 (0x7fd00001) Actual: 0 (0x0)
Line 150: assert_return FAILED Incorrect returned value. Expected: 9222246136947933185 (0x7ffc000000000001) Actual: 0 (0x0)
90 tests ran from float_memory.json.
  PASSED 48, FAILED 6, SKIPPED 36.

TOTAL 90 tests ran from "/home/andrei/dev/wasm-spec/test/core/json/float_memory/".
  PASSED 48, FAILED 6, SKIPPED 36.
```

With skipped:
```
> bin/fizzy-spectests ~/dev/wasm-spec/test/core/json/float_memory/ --show-skipped
Running tests from /home/andrei/dev/wasm-spec/test/core/json/float_memory/float_memory.json
..s..ssFs..s..s..s..ssFs..s..s..s..ssFs..s..s..s..ssFs..s..s..s..ssFs..s..s..s..ssFs..s..s
Line 16: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 19: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 20: action SKIPPED Unsupported feature: Floating point instruction.
Line 21: assert_return FAILED Incorrect returned value. Expected: 2141192192 (0x7fa00000) Actual: 0 (0x0)
Line 22: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 25: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 28: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 41: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 44: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 45: action SKIPPED Unsupported feature: Floating point instruction.
Line 46: assert_return FAILED Incorrect returned value. Expected: 9219994337134247936 (0x7ff4000000000000) Actual: 0 (0x0)
Line 47: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 50: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 53: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 68: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 71: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 72: action SKIPPED Unsupported feature: Floating point instruction.
Line 73: assert_return FAILED Incorrect returned value. Expected: 2141192192 (0x7fa00000) Actual: 0 (0x0)
Line 74: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 77: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 80: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 93: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 96: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 97: action SKIPPED Unsupported feature: Floating point instruction.
Line 98: assert_return FAILED Incorrect returned value. Expected: 9219994337134247936 (0x7ff4000000000000) Actual: 0 (0x0)
Line 99: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 102: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 105: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 120: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 123: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 124: action SKIPPED Unsupported feature: Floating point instruction.
Line 125: assert_return FAILED Incorrect returned value. Expected: 2144337921 (0x7fd00001) Actual: 0 (0x0)
Line 126: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 129: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 132: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 145: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 148: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 149: action SKIPPED Unsupported feature: Floating point instruction.
Line 150: assert_return FAILED Incorrect returned value. Expected: 9222246136947933185 (0x7ffc000000000001) Actual: 0 (0x0)
Line 151: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 154: assert_return SKIPPED Unsupported feature: Floating point instruction.
Line 157: assert_return SKIPPED Unsupported feature: Floating point instruction.
90 tests ran from float_memory.json.
  PASSED 48, FAILED 6, SKIPPED 36.

TOTAL 90 tests ran from "/home/andrei/dev/wasm-spec/test/core/json/float_memory/".
  PASSED 48, FAILED 6, SKIPPED 36.
```

Also supported are `--show-passed` and `--hide-failed`.

### CODE REVIEW

File: test/spectests/spectests.cpp [hunk 1]
```diff
@@ -98,12 +101,12 @@ class test_runner
...
             const auto type = cmd.at("type").get<std::string>();
 
-            log_no_newline("Line " + std::to_string(cmd.at("line").get<int>()) + ": " + type + " ");
+            m_current_line = cmd.at("line").get<int>();
+            m_current_test_type = type;
 
             if (type == "module")
             {
                 const auto filename = cmd.at("filename").get<std::string>();
-                log_no_newline("Instantiating " + filename + " ");
```
Comment (gumb0) [inline test/spectests/spectests.cpp:106]: Removing this, as I don't think it was very useful, and it would complicate things a bit to keep it.
The line will read just `Line X: module PASSED`

**Comment by chfast** [comment]
Looks nice. Just I would use lowercase `s` for skipped as in Python.

**Comment by gumb0** [comment]
> Looks nice. Just I would use lowercase `s` for skipped as in Python.

Changed.

**Comment by axic** [comment]
In order to not have reduced coverage, `ctest` should run spectests with the different combinations of parameters.
